name: Main Deployment

on:
  push:
    branches: [main, test]

env:
  PRIVATE_KEY: ${{secrets.SSH_KEY}}
  USER_NAME: ${{secrets.USERNAME}}
  HOSTNAME: ${{secrets.HOST}}
  FOLDER: "~/dap-strapi-cms"

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install --fronzen-lockfile
