  name: Main Deployment

on:
  push:
    branches: [main, test]

env:
  PRIVATE_KEY: ${{secrets.SSH_KEY}}
  USER_NAME: ${{secrets.USERNAME}}
  HOSTNAME: ${{secrets.HOST}}
  FOLDER: "~/dap-strapi-cms"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Deploy
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/dap-strapi-cms &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&
            npm install -g yarn &&
            yarn install --frozen-lockfile &&
            yarn build &&
            pm2 restart 0
            '
          
