name: Main Deployment

on:
  push:
    branches: [main, test]

env:
  PRIVATE_KEY: ${{secrets.SSH_KEY}}
  USER_NAME: ${{secrets.USERNAME}}
  HOSTNAME: ${{secrets.HOST}}
  FOLDER: "~/dap-strapi-cms"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: SSH to EC2
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}

      - name: Update Repository
        run: cd /home/ubuntu/dap-strapi-cms
